# Site settings
title: 赵丹丹的技术博客
email: cnzdd@live.cn
description: > # this means to ignore newlines until "baseurl:"
  技术分享 jekyll C# Java JavaScript CSS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://赵丹丹.中国" # the base hostname & protocol for your site
github_username:  cnryb


encoding: UTF-8

# Build settings
markdown: kramdown
highlighter: pygments
timezone: Asia/Shanghai